pipeline {
  agent any

	triggers {
		pollSCM('H/1 * * * *')
	}

	environment {
    KUBECONFIG = 'C:\\Users\\65911\\.kube\\config'
		TAG = "${BUILD_NUMBER}"
	}

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('raelene-part2-task-manager') {
          bat 'npm ci'
        }
      }
    }

    stage('Code Quality & Tests') {
      steps {
        dir('raelene-part2-task-manager') {
          bat 'npm test'
          bat 'npm run test-frontend'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('raelene-part2-task-manager') {
          bat "docker build -t taskbuddy-app:${TAG} ."
        }
      }
    }

    stage('Start Minikube') {
      steps {
        bat 'minikube start --ports=127.0.0.1:30080:30080'
      }
    }

    stage('Load Image to Minikube') {
      steps {
        bat "minikube image load taskbuddy-app:${TAG}"
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        dir('raelene-part2-task-manager') {
          bat """
						kubectl apply -f deployment.yaml
						kubectl set image deployment/taskbuddy-deploy taskbuddy-app=taskbuddy-app:${BUILD_NUMBER}
					"""
          bat 'kubectl apply -f service.yaml'
        }
      }
    }

    stage('Verify Rollout') {
      steps {
        bat 'kubectl get pods'
        bat 'kubectl get services'
      }
    }
  }
}
