pipeline {
  agent any

	triggers {
		pollSCM('H/1 * * * *')
	}

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('raelene-part2-task-manager') {
          bat 'npm ci'
        }
      }
    }

    stage('Code Tests') {
      steps {
        dir('raelene-part2-task-manager') {
          bat 'npm test'
          bat 'npm run test-frontend'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('raelene-part2-task-manager') {
          bat "docker build -t taskbuddy-app:${BUILD_NUMBER} ."
        }
      }
    }

    stage('Start Minikube') {
      steps {
        bat 'minikube status || minikube start --ports=127.0.0.1:30080:30080'
      }
    }

    stage('Load Image to Minikube') {
      steps {
        bat "minikube image load taskbuddy-app:${BUILD_NUMBER}"
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        dir('raelene-part2-task-manager') {
          bat """
						kubectl apply -f deployment.yaml
						kubectl set image deployment/taskbuddy-deploy taskbuddy-app=taskbuddy-app:${BUILD_NUMBER}
					"""
          bat 'kubectl apply -f service.yaml'
        }
      }
    }

    stage('Verify Rollout') {
      steps {
        bat 'kubectl get pods'
        bat 'kubectl get services'
      }
    }
  }

  post {
    success {
      emailext(
        subject: "✅ SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
        body: """
        <p>Build <b>SUCCESS</b></p>
        <p>
            Job: ${env.JOB_NAME}<br>
            Build Number: ${env.BUILD_NUMBER}<br>
            URL: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
        </p>
        """,
        to: "raelene.chaa@gmail.com",
        mimeType: 'text/html',
        from: "Taskbuddy CI <raelene.chaa@gmail.com>"
      )
    }

    failure {
      emailext(
        subject: "❌ FAILURE: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
        body: """
        <p>Build <b>FAILED</b></p>
        <p>
            Job: ${env.JOB_NAME}<br>
            Build Number: ${env.BUILD_NUMBER}<br>
            URL: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
        </p>
        """,
        to: "raelene.chaa@gmail.com",
        mimeType: 'text/html',
        from: "Taskbuddy CI <raelene.chaa@gmail.com>"
      )
    }
  }
}
